// src/docs/components/select/basicUsage.vue.tsx
import { options } from "data"
import { ref } from "vue"

const select = ref("value1");
export default () => {
  return (
    <>
      <l-select options={options} v-update:value={select.value} />
      <l-select options={options} v-update:value={select.value} readonly />
      <l-select options={options} v-update:value={select.value} disabled />
    </>
  );
}

// src/docs/components/range/basicUsage.vue.tsx
export default () => {
  return (
    <>
      <l-range value={30}></l-range>
      <l-range value={30} readonly></l-range>
      <l-range value={30} disabled></l-range>
      <l-range value={30} type="vertical"></l-range>
      <l-range value={30} type="vertical" readonly></l-range>
      <l-range value={30} type="vertical" disabled></l-range>
    </>
  );
};
